# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "holodisplays"
mod.name = "HoloDisplays"
mod.group = "dev.furq"
mod.version = "0.5.0"

deps.fabric_loader = "0.17.2"
deps.kotlin_version = "1.13.8+kotlin.2.3.0"
loomx.loom_version = "1.16-SNAPSHOT"

["1.20.6"]
mod.mc_dep = ">=1.20.5 <=1.21.1"
mod.mc_releases = ["1.20.6", "1.21", "1.21.1"]

deps.yarn_build = "3"
deps.fabric_api = "0.100.8+1.20.6"
deps.placeholder-api = "2.4.1+1.21"
deps.sgui = "1.6.1+1.21.1"
deps.permissions-api = "0.3.1"

["1.21.3"]
mod.mc_dep = ">=1.21.2 <=1.21.3"
mod.mc_releases = ["1.21.2", "1.21.3"]

deps.yarn_build = "2"
deps.fabric_api = "0.110.0+1.21.3"
deps.placeholder-api = "2.5.2+1.21.3"
deps.sgui = "1.7.2+1.21.2"
deps.permissions-api = "0.3.3"

["1.21.4"]
mod.mc_dep = ">=1.21.4 <=1.21.4"
mod.mc_releases = ["1.21.4"]

deps.yarn_build = "8"
deps.fabric_api = "0.119.3+1.21.4"
deps.placeholder-api = "2.5.2+1.21.3"
deps.sgui = "1.8.2+1.21.4"
deps.permissions-api = "0.3.3"

["1.21.5"]
mod.mc_dep = ">=1.21.5 <=1.21.5"
mod.mc_releases = ["1.21.5"]

deps.yarn_build = "1"
deps.fabric_api = "0.128.2+1.21.5"
deps.placeholder-api = "2.6.4+1.21.5"
deps.sgui = "1.9.1+1.21.5"
deps.permissions-api = "0.3.3"

["1.21.6"]
mod.mc_dep = ">=1.21.6 <=1.21.8"
mod.mc_releases = ["1.21.6", "1.21.7", "1.21.8"]

deps.yarn_build = "1"
deps.fabric_api = "0.128.2+1.21.6"
deps.placeholder-api = "2.7.2+1.21.8"
deps.sgui = "1.10.0+1.21.6"
deps.permissions-api = "0.4.1"

["1.21.10"]
mod.mc_dep = ">=1.21.9 <=1.21.10"
mod.mc_releases = ["1.21.9", "1.21.10"]

deps.yarn_build = "2"
deps.fabric_api = "0.136.0+1.21.10"
deps.placeholder-api = "2.8.0+1.21.9"
deps.sgui = "1.11.0+1.21.9"
deps.permissions-api = "0.5.0"

["1.21.11"]
mod.mc_dep = ">=1.21.11 <=1.21.11"
mod.mc_releases = ["1.21.11"]

deps.yarn_build = "3"
deps.fabric_api = "0.140.0+1.21.11"
deps.placeholder-api = "2.8.2+1.21.10"
deps.sgui = "1.12.0+1.21.11"
deps.permissions-api = "0.6.1"

["26.1"]
mod.mc_dep = "~26.1"
mod.mc_releases = ["26.1", "26.1.1", "26.1.2"]

deps.fabric_api = "0.145.1+26.1"
deps.placeholder-api = "3.0.0+26.1"
deps.sgui = "2.0.0+26.1"
deps.permissions-api = "0.6.1"
